// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "time"

type CurrentListDeps struct {
	CurrTask []map[string]string
}

func CurrentList(tasks CurrentListDeps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = CurrentListStyle().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"current-task-main\"><div class=\"current-task-container\"><div class=\"current-task-sublist\"><div class=\"current-task-sublist-title\">⚡️ next</div><div class=\"current-task-sublist-container\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, v := range tasks.CurrTask {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"current-task\" hx-get=\"/\" hx-trigger=\"click\" hx-target=\"#main-layout-form\" hx-swap=\"innerHTML\"><div class=\"task-title\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(v)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/layout/current-list.templ`, Line: 18, Col: 55}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><div class=\"task-deadline\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(v)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/layout/current-list.templ`, Line: 19, Col: 58}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div></div><div class=\"current-task-sublist\"><div class=\"current-task-sublist-title\">⚙️ projects</div><div class=\"current-task-sublist-container\">content</div></div><div class=\"current-task-sublist\"><div class=\"current-task-sublist-title\">📆 deadline</div><div class=\"current-task-sublist-container\">content</div></div><div class=\"current-task-sublist\"><div class=\"current-task-sublist-title\">🤝 delegate</div><div class=\"current-task-sublist-container\">content</div></div><div class=\"current-task-sublist\" style=\"margin-right: 2rem;\"><div class=\"current-task-sublist-title\">🔮 someday</div><div class=\"current-task-sublist-container\">content</div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func CurrentListStyle() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<style>\r\n        .current-task-main {\r\n            width: 200%;\r\n            height: inherit;\r\n            max-width: 200%;\r\n            max-height: inherit;\r\n            overflow-x: auto;\r\n            overflow-y: auto;\r\n            background-color: var(--color-black-002);\r\n        }\r\n        .current-task-container {\r\n            display: grid;\r\n            grid-template-columns: repeat(5, 1fr);;\r\n            height: fit-content;\r\n        }\r\n        .current-task-sublist {\r\n            margin: 2rem;\r\n            margin-right: 0;\r\n            border: 1px solid var(--color-black);\r\n            border-radius: 5px;\r\n            height: fit-content;\r\n            background-color: var(--color-white);\r\n        }\r\n        .current-task-sublist-title {\r\n            padding: 1rem;\r\n            border-bottom: 1px solid var(--color-black);\r\n        }\r\n        .current-task-sublist-container {\r\n            display: flex;\r\n            flex-direction: column;\r\n            margin: 1rem;\r\n            width: inherit;\r\n            height: fit-content;\r\n            gap: .5rem;\r\n        }\r\n        .current-task {\r\n            display: flex;\r\n            flex-direction: row;\r\n            border-radius: 5px;\r\n            justify-content: space-between;\r\n            align-items: center;\r\n            cursor: pointer;\r\n            padding-top: .5rem;\r\n            padding-bottom: .5rem;\r\n            border: 1px solid var(--color-black);\r\n        }\r\n        .current-task:hover {\r\n            background-color: var(--color-sidebar-button-hover);\r\n        }\r\n        .task-title {\r\n            margin-left: 1rem;\r\n        }\r\n        .task-deadline {\r\n            margin-right: 1rem;\r\n            color: var(--color-black-50);\r\n        }\r\n    </style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
